//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSql_Intro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTuccoEntities : DbContext
    {
        public DbTuccoEntities()
            : base("name=DbTuccoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APERATIF> APERATIF { get; set; }
        public virtual DbSet<ICECEKLER> ICECEKLER { get; set; }
        public virtual DbSet<KAHVALTI> KAHVALTI { get; set; }
        public virtual DbSet<PERSONEL> PERSONEL { get; set; }
        public virtual DbSet<SIPARISLER> SIPARISLER { get; set; }
        public virtual DbSet<TATLILAR> TATLILAR { get; set; }
        public virtual DbSet<YEMEKLER> YEMEKLER { get; set; }
    }
}
